[project]
name = "project-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "miller29601-collab", email = "miller29601@gamil.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
]

[project.scripts]
project-7 = "project_7:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
