[project]
name = "project-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "miller29601-collab", email = "miller29601@gamil.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.32.0",
    "fastapi[standard]>=0.142.2",
    "python-dotenv>=1.2.4",
]

[project.scripts]
project-7 = "project_7:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
[tool.mypy]
ignore_missing_imports = true

[dependency-groups]
dev = [
    "mypy>=2.4.0",
    "ruff>=0.16.10",
]
